"""
Module Contract
===============

Purpose:
    Orchestrate the PromptBuilder and the configured LLMProvider.
    Acts as the single point of entry for the application layer to request
    narrative summaries based on deterministic forecast reviews.

Consumes:
    - llm.prompt_builder.PromptBuilder
    - llm.gateway.LLMGateway
    - llm.prompts.SYSTEM_PROMPT (as default injection)

Produces:
    - Final generated narratives (Executive, Manager, Email, Teams).

Does NOT:
    - Directly instantiate API clients (e.g., Gemini).
    - Perform data processing, formatting, or business logic.
    - Inspect the underlying ReviewResult or pandas DataFrames.
    - Handle prompt creation logic directly.

Downstream Consumers:
    - app.py
    - External workflow triggers (FastAPI, Power Automate, Email Dispatcher)
"""

import logging

from llm.llm_provider import LLMProviderError
from llm.prompt_builder import PromptBuilder
from llm.prompts import SYSTEM_PROMPT
from llm.response_cleaner import ResponseCleaner
from llm.response_parser import ResponseParser
from models.summary_models import SummaryBundle
from llm.gateway import LLMGateway
from models.execution_context import ExecutionContext

logger = logging.getLogger(__name__)


class LLMService:
    """
    Stateless orchestration service linking the PromptBuilder to the active LLMProvider.
    """

    def __init__(
        self, 
        prompt_builder: PromptBuilder, 
        gateway: LLMGateway,
        system_prompt: str | None = None
    ) -> None:
        """
        Initialize the LLMService using strict dependency injection.

        Args:
            prompt_builder: Fully initialized PromptBuilder holding the pipeline context.
            gateway: LLMGateway handling provider abstraction and resilience.
            system_prompt: Optional override for the system prompt (e.g. for testing).
        """
        self.prompt_builder = prompt_builder
        self.gateway = gateway
        self.system_prompt = system_prompt if system_prompt is not None else SYSTEM_PROMPT
        logger.info("LLMService initialized with gateway.")

    def _compose_prompt(self, user_prompt: str) -> str:
        """
        Combine the universal system prompt with the target payload.
        Abstracted to easily support future message-based Chat APIs (e.g., OpenAI dicts)
        if the architecture transitions away from raw strings.
        
        Args:
            user_prompt: The rendered prompt payload.
            
        Returns:
            The fully assembled prompt string.
        """
        return f"{self.system_prompt}\n\n{user_prompt}"

    def _generate_response(self, user_prompt: str) -> str:
        """
        Combine instructions and invoke the provider.

        Args:
            user_prompt: The rendered prompt payload.

        Returns:
            The raw string response generated by the provider.

        Raises:
            LLMProviderError: If the underlying provider fails to complete the generation.
        """
        full_prompt = self._compose_prompt(user_prompt)

        try:
            logger.info("Provider invoked.")
            response = self.provider.generate(full_prompt)
            logger.info("Summary generated successfully.")
            return response
        except LLMProviderError as e:
            logger.error("Generation failed via provider %s: %s", self.provider.provider_name, str(e))
            raise
        except Exception as e:
            logger.error("Unexpected failure during generation: %s", str(e), exc_info=True)
            # Wrap generic exceptions in the domain exception
            raise LLMProviderError(f"Unexpected orchestration failure: {e}") from e

    def generate_all_summaries(self, context: ExecutionContext) -> SummaryBundle:
        """
        Generates all summaries in a single JSON response using the master prompt,
        cleans the response, parses it, and returns the strictly typed bundle.
        """
        logger.info("Master Prompt Built")
        prompt = self.prompt_builder.build_master_prompt()
        
        full_prompt = self._compose_prompt(prompt)

        try:
            logger.info("Gateway Invoked")
            raw_response, gateway_metrics = self.gateway.generate(full_prompt, context)
            logger.info("Response Received")
            
            clean_json = ResponseCleaner.clean(raw_response)
            
            # Use gateway metrics to identify the successful provider
            model_name = gateway_metrics[-1].model_name if gateway_metrics else "Gateway"
            provider_name = gateway_metrics[-1].provider_name if gateway_metrics else "Gateway"
            
            bundle = ResponseParser.parse_bundle(
                clean_json_str=clean_json,
                provider_name=provider_name,
                model_name=model_name
            )
            
            logger.info("JSON Parsed and SummaryBundle Created")
            return bundle
            
        except LLMProviderError as e:
            logger.error("Generation failed via gateway: %s", str(e))
            raise
        except Exception as e:
            logger.error("Unexpected failure during generation: %s", str(e), exc_info=True)
            raise LLMProviderError(f"Unexpected orchestration failure: {e}") from e

    def generate_executive_summary(self) -> str:
        """Request an executive-level summary targeting VP/Director stakeholders."""
        logger.info("Executive summary requested.")
        prompt = self.prompt_builder.build_executive_prompt()
        logger.info("Prompt generated.")
        return self._generate_response(prompt)

    def generate_manager_summary(self) -> str:
        """Request an operational summary targeting Forecast/Supply Chain managers."""
        logger.info("Manager summary requested.")
        prompt = self.prompt_builder.build_manager_prompt()
        logger.info("Prompt generated.")
        return self._generate_response(prompt)

    def generate_email_summary(self) -> str:
        """Request a professional email summary for enterprise distribution."""
        logger.info("Email summary requested.")
        prompt = self.prompt_builder.build_email_prompt()
        logger.info("Prompt generated.")
        return self._generate_response(prompt)

    def generate_teams_summary(self) -> str:
        """Request a concise Teams alert payload."""
        logger.info("Teams summary requested.")
        prompt = self.prompt_builder.build_teams_prompt()
        logger.info("Prompt generated.")
        return self._generate_response(prompt)
