"""
Module Contract
===============

Purpose:
    Provide a robust, stateless abstraction layer for all LLM communications.
    This ensures the deterministic analytics engine remains fully decoupled from
    any specific AI vendor or API.

Consumes:
    - Pre-rendered string prompts from PromptBuilder.
    - Configuration constants from config.settings.

Produces:
    - Raw string responses generated by the underlying language model.

Does NOT:
    - Import pandas, ReviewResult, or business analytics modules.
    - Build prompts from raw data.
    - Perform analytics or generate recommendations.
    - Parse JSON or Markdown out of the raw response.

Downstream Consumers:
    - FastAPI endpoints
    - Reporting generation services
"""

import logging
from abc import ABC, abstractmethod
from typing import Any

# Attempt to import the Google GenAI SDK. If not present, the code will fail gracefully
# only when a user attempts to instantiate GeminiProvider.
try:
    from google import genai
    from google.genai import types
    from google.genai.errors import APIError
    _GENAI_AVAILABLE = True
except ImportError:
    _GENAI_AVAILABLE = False

logger = logging.getLogger(__name__)


# =========================================================
# Custom Exceptions
# =========================================================

class LLMProviderError(Exception):
    """Base exception for all LLM-related failures."""

class LLMAuthenticationError(LLMProviderError):
    """Raised when the provider rejects credentials."""

class LLMNetworkError(LLMProviderError):
    """Raised when the network times out or drops connection."""

class LLMRateLimitError(LLMProviderError):
    """Raised when the provider enforces a rate limit or quota."""

class LLMSafetyError(LLMProviderError):
    """Raised when the provider blocks a request due to safety filters."""

class LLMEmptyResponseError(LLMProviderError):
    """Raised when the API succeeds but returns empty text."""


class LLMParseError(LLMProviderError):
    """Raised when the raw string response cannot be parsed as valid JSON."""


class ValidationError(LLMProviderError):
    """Raised when the parsed JSON fails strict domain validation constraints."""

# =========================================================
# Abstract Base Class
# =========================================================

class BaseLLMProvider(ABC):
    """
    Abstract interface for all language model providers.
    Guarantees a common invocation pattern (generate) regardless of the backend.
    """

    def __init__(self) -> None:
        logger.info("%s initialized.", self.__class__.__name__)

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Return the standardized name of this provider."""
        pass

    @abstractmethod
    def generate(self, prompt: str) -> str:
        """
        Send a strictly formatted prompt to the language model and return the text.
        
        Args:
            prompt: The complete, pre-rendered string prompt.
            
        Returns:
            The raw string response from the model.
            
        Raises:
            LLMProviderError: If any failure occurs during generation.
        """
        pass


# =========================================================
# Concrete Implementations
# =========================================================

class GeminiProvider(BaseLLMProvider):
    """
    Concrete implementation for the Google Gemini API using the official GenAI SDK.
    """

    def __init__(
        self,
        api_key: str,
        model: str,
        temperature: float,
        max_output_tokens: int,
        timeout_seconds: int,
        client: Any | None = None
    ) -> None:
        """
        Initialize the Gemini provider.
        
        Args:
            api_key: The API key for Google Gemini.
            model: The Gemini model string.
            temperature: Generation temperature.
            max_output_tokens: Maximum tokens to generate.
            timeout_seconds: Request timeout.
            client: An optional pre-configured genai.Client for dependency injection (e.g., testing).
        """
        super().__init__()
        
        if not _GENAI_AVAILABLE and client is None:
            raise RuntimeError(
                "The 'google-genai' package is not installed. "
                "Cannot initialize GeminiProvider without an injected client."
            )
            
        try:
            if client is not None:
                self.client = client
            else:
                if not api_key:
                    raise LLMAuthenticationError(
                        "GEMINI_API_KEY is missing or invalid."
                    )
                self.client = genai.Client(api_key=api_key)
                
            self.model_name = model
            logger.info("Gemini Model: %s", self.model_name)
            self.config = types.GenerateContentConfig(
                temperature=temperature,
                max_output_tokens=max_output_tokens,
            )
            self.timeout = timeout_seconds
            
        except Exception as e:
            raise LLMProviderError(f"Failed to initialize Gemini Client: {e}") from e

    @property
    def provider_name(self) -> str:
        return "Gemini Flash"

    def _extract_text(self, response: Any) -> str:
        """Centralized text extraction from a Gemini response object."""
        if not response:
            return ""
        # Access response text safely via object property or dict fallback
        try:
            text = response.text
        except AttributeError:
            text = getattr(response, "content", "")
            
        return text if isinstance(text, str) else ""

    def generate(self, prompt: str) -> str:
        """
        Execute a prompt against the configured Gemini model.
        """
        if not prompt or not prompt.strip():
            raise ValueError("Prompt cannot be empty.")
            
        logger.info("[%s] Prompt submitted to %s.", self.provider_name, self.model_name)
        
        try:
            # Using the official standard text generation call for google.genai
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
                config=self.config
            )
            
            logger.info("[%s] Response received.", self.provider_name)
            
            text_output = self._extract_text(response)
            
            if not text_output.strip():
                raise LLMEmptyResponseError("Gemini API returned an empty text response.")
                
            logger.info("[%s] Generation completed successfully.", self.provider_name)
            return text_output.strip()
            
        except APIError as api_err:
            logger.error("[%s] API Error encountered.", self.provider_name)
            
            status_code = getattr(api_err, "code", None)
            error_msg = str(api_err).lower()
            
            # Map API errors to our domain exceptions using status codes primarily, then string parsing
            if status_code == 429 or "quota" in error_msg or "rate limit" in error_msg:
                raise LLMRateLimitError(f"Rate limit exceeded: {api_err}") from api_err
                
            elif status_code in (401, 403) or "auth" in error_msg:
                raise LLMAuthenticationError(f"Authentication failed: {api_err}") from api_err
                
            elif "safety" in error_msg or "blocked" in error_msg:
                raise LLMSafetyError(f"Content blocked by safety filters: {api_err}") from api_err
                
            elif status_code in (504, 408) or "timeout" in error_msg or "deadline" in error_msg:
                raise LLMNetworkError(f"Network timeout: {api_err}") from api_err
                
            raise LLMProviderError(f"Unexpected Gemini API error [{status_code}]: {api_err}") from api_err
            
        except LLMProviderError:
            # Re-raise already mapped domain errors natively
            raise
            
        except Exception as e:
            logger.error("[%s] Unexpected error: %s", self.provider_name, str(e), exc_info=True)
            raise LLMProviderError(f"Unexpected generation failure: {e}") from e
