"""
Generates final markdown files from immutable SummaryBundle models.
Contains NO business logic, NO LLM interactions, and NO JSON parsing.
"""

import logging
from pathlib import Path

from models.summary_models import SummaryBundle

logger = logging.getLogger(__name__)


class MarkdownGenerator:
    """Writes strictly formatted markdown files from a SummaryBundle."""

    TEMPLATE = """\
# {title}

**Execution ID:** {execution_id}
**Generated By:** {provider} ({model})
**Generated At:** {generated_at}

---

{content}
"""

    @classmethod
    def generate_markdown_reports(cls, bundle: SummaryBundle, output_dir: Path) -> tuple[Path, Path, Path, Path]:
        """
        Writes all four summaries to the output directory.
        
        Args:
            bundle: The structured SummaryBundle.
            output_dir: Destination directory.
            
        Returns:
            Tuple containing the paths to the four generated files.
        """
        exec_path = output_dir / "executive_summary.md"
        mgr_path = output_dir / "manager_summary.md"
        email_path = output_dir / "email_summary.md"
        teams_path = output_dir / "teams_summary.md"

        cls._write_file(bundle.executive, exec_path, "Executive Summary")
        cls._write_file(bundle.manager, mgr_path, "Manager Summary")
        cls._write_file(bundle.email, email_path, "Email Summary")
        cls._write_file(bundle.teams, teams_path, "Teams Summary")
        
        logger.info("Markdown Files Generated successfully.")

        return exec_path, mgr_path, email_path, teams_path

    @classmethod
    def _write_file(cls, summary_obj, path: Path, title: str) -> None:
        """Helper to format and write a single summary."""
        from utils.logger import _context_filter
        
        content = cls.TEMPLATE.format(
            title=title,
            execution_id=getattr(_context_filter, "execution_id", "N/A"),
            provider=summary_obj.provider,
            model=summary_obj.model,
            generated_at=summary_obj.generated_at,
            content=summary_obj.content
        )
        try:
            path.write_text(content, encoding="utf-8")
        except OSError as e:
            logger.error("Failed to write markdown file %s: %s", path, e)
            raise
