"""
Pydantic v2 schemas for the FastAPI layer.

Defines API response contracts based on the canonical reporting schema.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict


class ProviderTelemetry(BaseModel):
    provider: str
    model: str
    circuit_state: str
    average_latency_ms: float
    total_calls: int
    total_retries: int
    last_success: Optional[str]
    last_failure: Optional[str]


class HealthResponse(BaseModel):
    """Schema for the /health endpoint."""
    status: str = Field(..., description="Overall health status of the API.")
    version: str = Field(..., description="Application version.")
    primary_provider: str = Field(..., description="Configured primary LLM provider.")
    secondary_provider: str = Field(..., description="Configured secondary LLM provider.")
    uptime: float = Field(..., description="Application uptime in seconds.")
    providers_telemetry: Dict[str, ProviderTelemetry] = Field(default_factory=dict, description="Live telemetry from the ProviderRegistry.")


class MetadataSchema(BaseModel):
    schema_version: str
    application_version: str
    generated_at: str
    generated_by: str
    environment: str


class PipelineSchema(BaseModel):
    status: str
    execution_time_seconds: float
    rows_processed: int
    modules_executed: List[str]
    failed_module: Optional[str] = None


class ValidationSchema(BaseModel):
    status: str
    warnings: int
    errors: int


class RecommendationsSchema(BaseModel):
    summary: Dict[str, Any]
    actions: List[Dict[str, Any]]


class ArtifactsSchema(BaseModel):
    directory: str
    html: str
    json: str
    executive_summary: str
    manager_summary: str
    email_summary: str
    teams_summary: str


class ForecastReviewResponse(BaseModel):
    """
    Schema for the /review POST endpoint.
    Mirrors the enterprise schema generated by JSONReportGenerator.
    """
    metadata: MetadataSchema
    pipeline: PipelineSchema
    validation: ValidationSchema
    performance: Dict[str, Any]
    comparison: Dict[str, Any]
    risk: Dict[str, Any]
    insights: Dict[str, Any]
    recommendations: RecommendationsSchema
    artifacts: ArtifactsSchema
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "metadata": {
                    "schema_version": "1.0",
                    "application_version": "1.0.0",
                    "generated_at": "2026-07-01T12:00:00Z",
                    "generated_by": "Forecast Review System",
                    "environment": "production"
                },
                "pipeline": {
                    "status": "SUCCESS",
                    "execution_time_seconds": 12.5,
                    "rows_processed": 1050,
                    "modules_executed": ["validation", "performance", "insights"],
                    "failed_module": None
                },
                "validation": {
                    "status": "PASS",
                    "warnings": 0,
                    "errors": 0
                },
                "performance": {},
                "comparison": {},
                "risk": {},
                "insights": {},
                "recommendations": {
                    "summary": {},
                    "actions": []
                },
                "artifacts": {
                    "directory": "/tmp/forecast_review_api_abc123",
                    "html": "forecast_review.html",
                    "json": "forecast_review.json",
                    "executive_summary": "executive_summary.md",
                    "manager_summary": "manager_summary.md",
                    "email_summary": "email_summary.md",
                    "teams_summary": "teams_summary.md"
                }
            }
        }
    )
